using Content.Client.Message;
using Content.Shared.Backmen.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Backmen.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class BankUiFragment : BoxContainer
{
    public BankUiFragment()
    {
        RobustXamlLoader.Load(this);
    }
    public void UpdateState(BankUiState state)
    {
        bool noAccount = false;
        if (state.LinkedAccountNumber == null)
            noAccount = true;

        NoLinkedAccount.Visible = noAccount;
        LinkedAccount.Visible = !noAccount;
        LinkedAccountNumberLabel.SetMarkup(Loc.GetString("bank-program-account-number", ("number", state.LinkedAccountNumber ?? "???")));
        LinkedAccountNameLabel.SetMarkup(Loc.GetString("bank-program-account-name", ("name", state.LinkedAccountName ?? "???")));
        LinkedAccountBalanceLabel.SetMarkup(Loc.GetString("bank-program-account-balance", ("balance", state.LinkedAccountBalance ?? 0), ("currencySymbol", state.CurrencySymbol ?? "")));
    }
}
