using System.Linq;
using Content.Client.UserInterface.Screens;
using Content.Shared.CCVar;
using Content.Shared.HUD;
using Robust.Client.AutoGenerated;
using Robust.Client.Player;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Prototypes;
using Content.Shared.Backmen.CCVar;

namespace Content.Client.Options.UI.Tabs;

[GenerateTypedNameReferences]
public sealed partial class MiscTab : Control
{
    [Dependency] private readonly IPlayerManager _playerManager = default!;
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

    public MiscTab()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var themes = _prototypeManager.EnumeratePrototypes<HudThemePrototype>().ToList();
        themes.Sort();
        var themeEntries = new List<OptionDropDownCVar<string>.ValueOption>();
        foreach (var gear in themes)
        {
            themeEntries.Add(new OptionDropDownCVar<string>.ValueOption(gear.ID, Loc.GetString(gear.Name)));
        }

        var layoutEntries = new List<OptionDropDownCVar<string>.ValueOption>();
        foreach (var layout in Enum.GetValues(typeof(ScreenType)))
        {
            layoutEntries.Add(new OptionDropDownCVar<string>.ValueOption(layout.ToString()!, Loc.GetString($"ui-options-hud-layout-{layout.ToString()!.ToLower()}")));
        }

        // Channel can be null in replays so.
        // ReSharper disable once ConditionalAccessQualifierIsNonNullableAccordingToAPIContract
        ShowOocPatronColor.Visible = _playerManager.LocalSession?.Channel?.UserData.PatronTier is { };
        // Backmen-Edit-START
        Control.AddOptionDropDown(CVars.InterfaceTheme, DropDownHudTheme, themeEntries);
        Control.AddOptionDropDown(Shared.CCVar.CCVars.UILayout, DropDownHudLayout, layoutEntries);

        Control.AddOptionCheckBox(CVars.DiscordEnabled, DiscordRich);
        Control.AddOptionCheckBox(Shared.CCVar.CCVars.ShowOocPatronColor, ShowOocPatronColor);
        Control.AddOptionCheckBox(Shared.CCVar.CCVars.LoocAboveHeadShow, ShowLoocAboveHeadCheckBox);
        Control.AddOptionCheckBox(Shared.Backmen.CCVar.CCVars.LogInChat, LogInChatCheckBox); // Backmen
        Control.AddOptionCheckBox(Shared.Backmen.CCVar.CCVars.CoalesceIdenticalMessages, CoalesceIdenticalMessagesCheckBox); // Backmen
        Control.AddOptionCheckBox(Shared.Backmen.CCVar.CCVars.DetailedExamine, DetailedExamineCheckBox); // Backmen
        Control.AddOptionCheckBox(Shared.CCVar.CCVars.HudHeldItemShow, ShowHeldItemCheckBox);
        Control.AddOptionCheckBox(Shared.CCVar.CCVars.CombatModeIndicatorsPointShow, ShowCombatModeIndicatorsCheckBox);
        Control.AddOptionCheckBox(Shared.CCVar.CCVars.OpaqueStorageWindow, OpaqueStorageWindowCheckBox);
        Control.AddOptionCheckBox(Shared.CCVar.CCVars.ChatEnableFancyBubbles, FancySpeechBubblesCheckBox);
        Control.AddOptionCheckBox(Shared.CCVar.CCVars.ChatFancyNameBackground, FancyNameBackgroundsCheckBox);
        Control.AddOptionCheckBox(Shared.CCVar.CCVars.StaticStorageUI, StaticStorageUI);
        Control.AddOptionCheckBox(Shared.Backmen.CCVar.CCVars.OfferModeIndicatorsPointShow, ShowOfferModeIndicatorsCheckBox);
        Control.Initialize();
    }   // Backmen-Edit-END
}
