# ruined hospital

- type: entityTable
  id: RuinedHospitalDoor
  table: !type:AllSelector
    children:
    - id: CableApcExtension
    - id: AirlockGlass

- type: dungeonConfig
  id: RuinedHospital
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - RuinedHospital
    presets:
    - NyanoCompound
    fallbackTile: FloorWhitePlastic
  - !type:CorridorDunGen
    width: 3
    tile: FloorWhitePlastic
  - !type:EntranceFlankDunGen
    contents: DungeonWindow
    tile: FloorDark
  - !type:JunctionDunGen
    width: 1
    tile: Plating
    contents: BaseAirlock
  - !type:WallMountDunGen
    contents: RuinedHospitalWalls
    tile: FloorSteel

  - !type:DungeonEntranceDunGen
    count: 2
    tile: FloorWhitePlastic
    contents: RuinedHospitalDoor

  - !type:RoomEntranceDunGen
    tile: FloorWhitePlastic
    contents: RuinedHospitalDoor

  - !type:WallMountDunGen
    contents: RuinedHospitalWalls
    tile: Plating
    prob: 0.05

  - !type:AutoCablingDunGen
    entity: CableApcExtension

  - !type:BoundaryWallDunGen
    tile: Plating
    wall: WallDrywall
    cornerWall: WallDrywall

  - !type:EntityTableDunGen
    minCount: 1
    maxCount: 1
    perDungeon: false
    table: !type:NestedSelector
      tableId: ShipwreckGuaranteedScrewdriver

  - !type:EntityTableDunGen
    minCount: 4
    maxCount: 10
    table: !type:NestedSelector
      tableId: ShipwreckDungeonToolsTable

- type: entityTable
  id: RuinedHospitalWalls
  table: !type:GroupSelector
    children:
      - id: RandomPainting
        prob: 1
      - id: DefibrillatorCabinetFilled
        prob: 0.2
      - id: ExtinguisherCabinetFilled
        prob: 0.2
      - id: IntercomCommon
        prob: 0.1

# ruined dwellings

- type: entitySpawnEntry
  id: RuinedDwellingsDoor
  entries:
  - id: CableApcExtension
  - id: WoodDoor

- type: entitySpawnEntry
  id: RuinedDwellingsEntranceFlank
  entries:
  - id: CableApcExtension
  - id: WallPaper

- type: dungeonConfig
  id: RuinedDwellings
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - RuinedDwelling
    presets:
    - NyanoStack
    fallbackTile: FloorWood
  - !type:CornerClutterDunGen
    contents: BaseClutter
  - !type:EntranceFlankDunGen
    contents: DungeonWindow
    tile: FloorDark
  - !type:JunctionDunGen
    width: 1
    tile: FloorWood
    contents: RuinedDwellingsAirlock
  - !type:WallMountDunGen
    contents: RuinedDwellingsWalls
    tile: FloorSteel

  - !type:DungeonEntranceDunGen
    count: 2
    tile: FloorWood
    contents: RuinedDwellingsAirlock

  - !type:RoomEntranceDunGen
    tile: FloorWood
    contents: RuinedDwellingsAirlock

  - !type:ExternalWindowDunGen
    tile: FloorWood
    contents: DungeonWindow

  - !type:AutoCablingDunGen
    entity: CableApcExtension

  - !type:WallMountDunGen
    tile: Plating
    prob: 0.05
    contents: RuinedDwellingsWalls

  - !type:BoundaryWallDunGen
    tile: Plating
    wall: WallDrywall
    cornerWall: WallDrywall

  - !type:EntityTableDunGen
    minCount: 1
    maxCount: 1
    perDungeon: false
    table: !type:NestedSelector
      tableId: ShipwreckGuaranteedScrewdriver

  - !type:EntityTableDunGen
    minCount: 4
    maxCount: 10
    table: !type:NestedSelector
      tableId: ShipwreckDungeonToolsTable

- type: entityTable
  id: RuinedDwellingsWalls
  table: !type:GroupSelector
    children:
    # Posters
    - id: RandomPainting

- type: entityTable
  id: RuinedDwellingsAirlock
  table: !type:AllSelector
    children:
    - id: CableApcExtension
    - id: WoodDoor

# ruined shops

- type: entityTable
  id: RuinedShopDoor
  table: !type:AllSelector
    children:
    - id: CableApcExtension
    - id: WoodDoor

- type: dungeonConfig
  id: RuinedShop
  layers:
  - !type:PrefabDunGen
    roomWhitelist:
      tags:
      - RuinedShop
    presets:
    - NyanoSolo9
    fallbackTile: FloorWood
  - !type:CornerClutterDunGen
    contents: BaseClutter
  - !type:EntranceFlankDunGen
    contents: DungeonWindow
    tile: FloorDark
  - !type:JunctionDunGen
    width: 1
    tile: Plating
    contents: RuinedShopDoor
  - !type:WallMountDunGen
    contents: RuinedDwellingsWalls
    tile: FloorSteel
  - !type:BoundaryWallDunGen
    tile: Plating
    wall: WallDrywall
    cornerWall: WallDrywall
  - !type:DungeonEntranceDunGen
    count: 4
    tile: FloorWood
    contents: RuinedShopDoor
  - !type:RoomEntranceDunGen
    tile: FloorWood
    contents: RuinedShopDoor
  - !type:AutoCablingDunGen
    entity: CableApcExtension

  - !type:EntityTableDunGen
    minCount: 1
    maxCount: 1
    perDungeon: false
    table: !type:NestedSelector
      tableId: ShipwreckGuaranteedScrewdriver

  - !type:EntityTableDunGen
    minCount: 4
    maxCount: 10
    table: !type:NestedSelector
      tableId: ShipwreckDungeonToolsTable

- type: entitySpawnEntry
  id: ShopWoodDoor
  entries:
  - id: WoodDoor

- type: entitySpawnEntry
  id: ShopWall
  entries:
  - id: WallDrywall

- type: entityTable
  id: DungeonWindow
  table: !type:AllSelector
    children:
    - id: CableApcExtension
    - id: Grille
    - id: Window
