using Robust.Client.AutoGenerated;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared;
using Robust.Shared.Configuration;

namespace Content.Client.MainMenu.UI;

[GenerateTypedNameReferences]
public sealed partial class MainMenuControl : Control
{
    public MainMenuControl(IResourceCache resCache, IConfigurationManager configMan)
    {
        RobustXamlLoader.Load(this);

        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

        LayoutContainer.SetAnchorPreset(VBox, LayoutContainer.LayoutPreset.Center);
        LayoutContainer.SetGrowHorizontal(VBox, LayoutContainer.GrowDirection.Both);
        LayoutContainer.SetGrowVertical(VBox, LayoutContainer.GrowDirection.Both);

        var currentUserName = configMan.GetCVar(CVars.PlayerName);
        UsernameBox.Text = currentUserName;
    }
}
