using Content.Shared._Backmen.Reinforcement;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Backmen.Economy.WageConsole.UI;

[GenerateTypedNameReferences]
public sealed partial class WageRow : PanelContainer
{
    public uint Id { get; set; }

    public WageRow()
    {
        RobustXamlLoader.Load(this);
    }
}
