using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using System.Numerics;

namespace Content.Client.Backmen.TerrorSpider;

[GenerateTypedNameReferences]
public sealed partial class EggsLayingMenu : RadialMenu
{
    [Dependency] private readonly EntityManager _entManager = default!;

    private SpriteSystem? _sprites;

    public event Action<EntProtoId>? EggChosen;

    public EggsLayingMenu()
    {
        IoCManager.InjectDependencies(this);
        RobustXamlLoader.Load(this);

        _sprites = _entManager.System<SpriteSystem>();

        Refresh();
        Open();
    }

    public void Refresh()
    {
        var main = FindControl<RadialContainer>("Main");

//        AddButton(main, "Queen", _sprites!.GetPrototypeIcon("MobTerrorSpiderQueen").TextureFor(Direction.South), "TerrorSpiderQueenEgg");
//        AddButton(main, "Mother", _sprites!.GetPrototypeIcon("MobTerrorSpiderMother").TextureFor(Direction.South), "TerrorSpiderMotherEgg");
//        AddButton(main, "Princess", _sprites!.GetPrototypeIcon("MobTerrorSpiderPrincess").TextureFor(Direction.South), "TerrorSpiderPrincessEgg");
//        AddButton(main, "Prince", _sprites!.GetPrototypeIcon("MobTerrorSpiderPrince").TextureFor(Direction.South), "TerrorSpiderPrinceEgg");
        AddButton(main, "Destroyer", _sprites!.GetPrototypeIcon("MobTerrorSpiderDestroyer").TextureFor(Direction.South), "TerrorSpiderDestroyerEgg");
        AddButton(main, "Guardian", _sprites!.GetPrototypeIcon("MobTerrorSpiderGuardian").TextureFor(Direction.South), "TerrorSpiderGuardianEgg");
        AddButton(main, "Defiler", _sprites!.GetPrototypeIcon("MobTerrorSpiderDefiler").TextureFor(Direction.South), "TerrorSpiderDefilerEgg");
        AddButton(main, "Widow", _sprites!.GetPrototypeIcon("MobTerrorSpiderWidow").TextureFor(Direction.South), "TerrorSpiderWidowEgg");
        AddButton(main, "Reaper", _sprites!.GetPrototypeIcon("MobTerrorSpiderReaper").TextureFor(Direction.South), "TerrorSpiderReaperEgg");
        AddButton(main, "Drone", _sprites!.GetPrototypeIcon("MobTerrorSpiderDrone").TextureFor(Direction.South), "TerrorSpiderDroneEgg");
        AddButton(main, "Healer", _sprites!.GetPrototypeIcon("MobTerrorSpiderHealer").TextureFor(Direction.South), "TerrorSpiderHealerEgg");
        AddButton(main, "Lurker", _sprites!.GetPrototypeIcon("MobTerrorSpiderLurker").TextureFor(Direction.South), "TerrorSpiderLurkerEgg");
        AddButton(main, "Knight", _sprites!.GetPrototypeIcon("MobTerrorSpiderKnight").TextureFor(Direction.South), "TerrorSpiderKnightEgg");
    }

    private void AddButton(RadialContainer main, string tooltip, Texture sprite, string prototype)
    {
        var button = new MenuButton
        {
            StyleClasses = { "RadialMenuButton" },
            SetSize = new Vector2(64f, 64f),
            ToolTip = tooltip,
        };

        var tex = new TextureRect
        {
            VerticalAlignment = VAlignment.Center,
            HorizontalAlignment = HAlignment.Center,
            Texture = sprite,
            TextureScale = new Vector2(2f, 2f),
        };

        button.OnButtonUp += _ => EggChosen?.Invoke(prototype);
        button.AddChild(tex);
        main.AddChild(button);
    }
}

public sealed class MenuButton : RadialMenuTextureButton
{
    public MenuButton()
    {
    }
}
