using Content.Shared.Backmen.Shipyard.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Backmen.Shipyard.UI;

[GenerateTypedNameReferences]
public sealed partial class VesselRow : PanelContainer
{
    public VesselPrototype? Vessel { get; set; }

    public VesselRow()
    {
        RobustXamlLoader.Load(this);
    }
}
