using Content.Client.Lathe;
using Content.Client.Research;
using Content.Client.Research.UI;
using Content.Shared.Backmen.Research;
using Content.Shared.Research.Components;
using Content.Shared.Research.Prototypes;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.GameObjects;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Backmen.Research.UI;

[GenerateTypedNameReferences]
public sealed partial class FancyTechnologyInfoPanel : Control
{
    [Dependency] private IEntityManager _ent = default!;
    [Dependency] private IPrototypeManager _proto = default!;

    public TechnologyPrototype Prototype;
    public Action<TechnologyPrototype>? BuyAction;
    public FancyTechnologyInfoPanel(
        TechnologyPrototype proto,
        bool hasAccess,
        ResearchAvailability availability,
        SpriteSystem sprite,
        TechnologyDatabaseComponent? database = null) // backmen: rnd-console-prereqs
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        var lathe = _ent.System<LatheSystem>();
        var research = _ent.System<ResearchSystem>();
        Prototype = proto;

        TechnologyNameLabel.Text = Loc.GetString(proto.Name);
        DisciplineTexture.Texture = sprite.Frame0(_proto.Index(proto.Discipline).Icon);
        TechnologyTexture.Texture = sprite.Frame0(proto.Icon);

        InitializePrerequisites(proto, research, sprite, database); // backmen: rnd-console-prereqs

        InitializeRecipeUnlocks(proto, lathe, sprite);

        ResearchButton.ToolTip = !hasAccess
            ? Loc.GetString("research-console-no-access-popup")
            : null;

        ResearchButton.Text = availability == ResearchAvailability.Researched
            ? Loc.GetString("research-console-menu-server-researched-button")
            : ResearchButton.Text;

        Color? color = availability switch
        {
            ResearchAvailability.Researched => Color.LimeGreen,
            ResearchAvailability.PrereqsMet => Color.Crimson,
            ResearchAvailability.Unavailable => Color.Crimson,
            _ => null
        };
        TechnologyCostLabel.SetMessage(
            Loc.GetString("research-console-tech-cost-label", ("cost", proto.Cost)),
            defaultColor: color
        );

        ResearchButton.Disabled = !hasAccess || availability != ResearchAvailability.Available;
        ResearchButton.OnPressed += Bought;
    }

    private void InitializePrerequisites(
        TechnologyPrototype proto,
        ResearchSystem research,
        SpriteSystem sprite,
        TechnologyDatabaseComponent? database)
    {
        // start-backmen: rnd-console-prereqs
        var hasRequirements = BkmResearchRequirements.HasUnmetRequirements(research, proto, database, _proto);
        NoPrereqLabel.Visible = !hasRequirements;
        PrereqsContainer.Visible = hasRequirements;

        RequiredTechContainer.RemoveAllChildren();

        foreach (var techId in proto.TechnologyPrerequisites)
        {
            if (database != null && research.IsTechnologyUnlocked(EntityUid.Invalid, techId, database))
                continue;

            var tech = _proto.Index(techId);
            var description = research.GetTechnologyDescription(tech, true, false, true);
            RequiredTechContainer.AddChild(new MiniTechnologyCardControl(tech, _proto, sprite, description));
        }

        if (database == null)
            return;

        var discipline = _proto.Index(proto.Discipline);

        if (BkmResearchRequirements.IsDisciplineLockoutBlocking(research, proto, database, discipline))
        {
            var mainDiscipline = _proto.Index<TechDisciplinePrototype>(database.MainDiscipline!);
            var lockoutLabel = new RichTextLabel();
            lockoutLabel.SetMessage(Loc.GetString("research-console-discipline-lockout-requirement",
                ("discipline", Loc.GetString(discipline.Name)),
                ("color", discipline.Color),
                ("mainDiscipline", Loc.GetString(mainDiscipline.Name)),
                ("mainColor", mainDiscipline.Color)));
            RequiredTechContainer.AddChild(lockoutLabel);
        }
        else if (!BkmResearchRequirements.IsTierRequirementMet(research, proto, database)
                 && discipline.TierPrerequisites.TryGetValue(proto.Tier, out var requiredRatio))
        {
            var previousTier = proto.Tier - 1;
            var currentProgress = (int) (BkmResearchRequirements.GetTierProgress(research, database, discipline, previousTier, _proto) * 100f);
            var requiredProgress = (int) (requiredRatio * 100f);
            var tierLabel = new RichTextLabel();
            tierLabel.SetMessage(Loc.GetString("research-console-tier-requirement",
                ("percent", requiredProgress),
                ("tier", previousTier),
                ("discipline", Loc.GetString(discipline.Name)),
                ("color", discipline.Color),
                ("current", currentProgress)));
            RequiredTechContainer.AddChild(tierLabel);
        }
        // end-backmen: rnd-console-prereqs
    }

    private void InitializeRecipeUnlocks(TechnologyPrototype proto, LatheSystem lathe, SpriteSystem sprite)
    {
        UnlocksContainer.RemoveAllChildren();
        foreach (var recipeId in proto.RecipeUnlocks)
        {
            var recipe = _proto.Index(recipeId);
            UnlocksContainer.AddChild(new MiniRecipeCardControl(proto, recipe, _proto, sprite, lathe));
        }
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();

        ResearchButton.OnPressed -= Bought;
    }
    private void Bought(BaseButton.ButtonEventArgs args)
    {
        BuyAction?.Invoke(Prototype);
    }

}
