# LuaWorld - This file is licensed under AGPLv3
# Copyright (c) 2025 LuaWorld Contributors
# See AGPLv3.txt for details.

- type: entity
  parent: MobHuman
  id: BaseMobHuman
  abstract: true
  save: false
