using System.Linq;
using Content.Client.Backmen.Language.Systems;
using Content.Shared.Backmen.Language;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;

namespace Content.Client.Backmen.Language;

[GenerateTypedNameReferences]
public sealed partial class LanguageMenuWindow : DefaultWindow
{
    private readonly LanguageSystem _clientLanguageSystem;
    private readonly Dictionary<ProtoId<LanguagePrototype>, EntryState> _entriesByLanguage = new();
    private ProtoId<LanguagePrototype>? _cachedCurrent;
    private HashSet<ProtoId<LanguagePrototype>> _cachedSpoken = [];

    public LanguageMenuWindow()
    {
        RobustXamlLoader.Load(this);
        _clientLanguageSystem = IoCManager.Resolve<IEntitySystemManager>().GetEntitySystem<LanguageSystem>();
    }

    protected override void EnteredTree()
    {
        base.EnteredTree();
        _clientLanguageSystem.OnLanguagesChanged += OnUpdateState;
    }

    protected override void ExitedTree()
    {
        base.ExitedTree();
        _clientLanguageSystem.OnLanguagesChanged -= OnUpdateState;
    }

    protected override void Opened()
    {
        UpdateState(_clientLanguageSystem.CurrentLanguage, _clientLanguageSystem.SpokenLanguages);
    }

    private void OnUpdateState(object? sender, Entity<LanguageSpeakerComponent> args)
    {
        if (!IsOpen)
            return;

        UpdateState(args.Comp.CurrentLanguage, args.Comp.SpokenLanguages);
    }

    private void UpdateState(ProtoId<LanguagePrototype>? currentLanguage, HashSet<ProtoId<LanguagePrototype>> spokenLanguages)
    {
        var langName = currentLanguage is { } id
            ? Loc.GetString($"language-{id}-name")
            : Loc.GetString("generic-error");
        CurrentLanguageLabel.Text = Loc.GetString("language-menu-current-language", ("language", langName));

        if (_cachedCurrent == currentLanguage && _cachedSpoken.SetEquals(spokenLanguages))
            return;

        if (_cachedSpoken.SetEquals(spokenLanguages) && _cachedCurrent != currentLanguage)
        {
            _cachedCurrent = currentLanguage;
            UpdateButtonStates(currentLanguage);
            return;
        }

        _cachedCurrent = currentLanguage;
        _cachedSpoken = new HashSet<ProtoId<LanguagePrototype>>(spokenLanguages);

        foreach (var language in _entriesByLanguage.Keys.Except(spokenLanguages).ToArray())
            RemoveLanguageEntry(language);

        var sorted = spokenLanguages
            .Select(id => (id, _clientLanguageSystem.GetLanguagePrototype(id)))
            .OrderBy(x => x.Item2?.Name ?? x.id)
            .Select(x => x.id);

        foreach (var language in sorted)
        {
            if (!_entriesByLanguage.ContainsKey(language))
                AddLanguageEntry(language);
        }

        UpdateButtonStates(currentLanguage);
    }

    private void UpdateButtonStates(ProtoId<LanguagePrototype>? currentLanguage)
    {
        foreach (var (language, entry) in _entriesByLanguage)
        {
            if (entry.Button != null)
                entry.Button.Disabled = language == currentLanguage;
        }
    }

    private void RemoveLanguageEntry(ProtoId<LanguagePrototype> language)
    {
        if (!_entriesByLanguage.TryGetValue(language, out var entry))
            return;

        entry.Wrapper?.Orphan();
        _entriesByLanguage.Remove(language);
    }

    private void AddLanguageEntry(ProtoId<LanguagePrototype> language)
    {
        var proto = _clientLanguageSystem.GetLanguagePrototype(language);

        var header = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
            SeparationOverride = 2
        };

        var name = new Label
        {
            Text = proto?.Name ?? Loc.GetString("generic-error"),
            MinWidth = 50,
            HorizontalExpand = true
        };

        var button = new Button { Text = Loc.GetString("language-menu-choose") };
        button.OnPressed += _ => OnLanguageChosen(language);

        if (!string.IsNullOrEmpty(proto?.Description))
            name.ToolTip = proto.Description;

        header.AddChild(name);
        header.AddChild(button);

        var wrapper = new PanelContainer();
        wrapper.StyleClasses.Add("PdaBorderRect");
        wrapper.AddChild(header);
        OptionsList.AddChild(wrapper);

        _entriesByLanguage[language] = new EntryState { Wrapper = wrapper, Button = button };
    }

    private void OnLanguageChosen(ProtoId<LanguagePrototype> id)
    {
        var proto = _clientLanguageSystem.GetLanguagePrototype(id);
        if (proto == null)
            return;

        _clientLanguageSystem.RequestSetLanguage(proto);
    }

    private sealed class EntryState
    {
        public PanelContainer? Wrapper;
        public Button? Button;
    }
}
