using System.Diagnostics.CodeAnalysis;
using System.Linq;
using Content.Client.Message;
using Content.Client.UserInterface.Controls;
using Content.Shared.Backmen.Supermatter.Consoles;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;
using Robust.Shared.Utility;

namespace Content.Client.Backmen.Supermatter.Consoles;

[GenerateTypedNameReferences]
public sealed partial class SupermatterConsoleWindow : FancyWindow
{
    private readonly IEntityManager _entManager;

    private readonly EntityUid? _owner;
    private NetEntity? _trackedEntity;

    private SupermatterConsoleEntry[]? _supermatters;

    public event Action<NetEntity?>? SendFocusChangeMessageAction;

    private bool _autoScrollActive;
    private bool _autoScrollAwaitsUpdate;

    public SupermatterConsoleWindow(SupermatterConsoleBoundUserInterface userInterface, EntityUid? owner)
    {
        RobustXamlLoader.Load(this);
        _entManager = IoCManager.Resolve<IEntityManager>();

        _owner = owner;
        SendFocusChangeMessageAction += userInterface.SendFocusChangeMessage;
    }

    public void UpdateUI(SupermatterConsoleEntry[] supermatters, SupermatterFocusData? focusData)
    {
        if (_owner == null
            || !_entManager.TryGetComponent<SupermatterConsoleComponent>(_owner.Value, out var console))
            return;

        if (_trackedEntity != focusData?.NetEntity)
        {
            SendFocusChangeMessageAction?.Invoke(_trackedEntity);
            focusData = null;
        }

        _supermatters = supermatters;

        var supermattersCount = _supermatters.Length;

        while (SupermattersTable.ChildCount > supermattersCount)
            SupermattersTable.RemoveChild(SupermattersTable.GetChild(SupermattersTable.ChildCount - 1));

        for (var index = 0; index < _supermatters.Length; index++)
        {
            var entry = _supermatters[index];
            UpdateUIEntry(entry, index, SupermattersTable, console, focusData);
        }

        if (supermattersCount == 0)
        {
            var label = new RichTextLabel
            {
                HorizontalExpand = true,
                VerticalExpand = true,
                HorizontalAlignment = HAlignment.Center,
                VerticalAlignment = VAlignment.Center,
            };

            label.SetMarkup(Loc.GetString("supermatter-console-window-no-supermatters"));
            SupermattersTable.AddChild(label);
        }

        if (_autoScrollAwaitsUpdate)
        {
            _autoScrollActive = true;
            _autoScrollAwaitsUpdate = false;
        }
    }

    private void UpdateUIEntry(
        SupermatterConsoleEntry entry,
        int index,
        Control table,
        SupermatterConsoleComponent console,
        SupermatterFocusData? focusData = null)
    {
        if (index >= table.ChildCount)
        {
            var newEntryContainer = new SupermatterEntryContainer(entry.NetEntity);

            newEntryContainer.FocusButton.OnButtonUp += _ =>
            {
                _trackedEntity = _trackedEntity == newEntryContainer.NetEntity
                    ? null
                    : newEntryContainer.NetEntity;

                SendFocusChangeMessageAction?.Invoke(_trackedEntity);
            };

            table.AddChild(newEntryContainer);
        }

        var tableChild = table.GetChild(index);

        if (tableChild is not SupermatterEntryContainer)
        {
            table.RemoveChild(tableChild);
            UpdateUIEntry(entry, index, table, console, focusData);
            return;
        }

        var entryContainer = (SupermatterEntryContainer) tableChild;
        entryContainer.UpdateEntry(entry, entry.NetEntity == _trackedEntity, focusData);
    }

    protected override void FrameUpdate(FrameEventArgs args) =>
        AutoScrollToFocus();

    private void AutoScrollToFocus()
    {
        if (!_autoScrollActive)
            return;

        var scroll = SupermattersTable.Parent as ScrollContainer;
        if (scroll == null
            || !TryGetVerticalScrollbar(scroll, out var vScrollbar)
            || !TryGetNextScrollPosition(out var nextScrollPosition))
            return;

        vScrollbar.ValueTarget = nextScrollPosition.Value;

        if (MathHelper.CloseToPercent(vScrollbar.Value, vScrollbar.ValueTarget))
            _autoScrollActive = false;
    }

    private static bool TryGetVerticalScrollbar(ScrollContainer scroll, [NotNullWhen(true)] out VScrollBar? vScrollBar)
    {
        vScrollBar = null;

        foreach (var child in scroll.Children)
        {
            if (child is not VScrollBar castChild)
                continue;

            vScrollBar = castChild;
            return true;
        }

        return false;
    }

    private bool TryGetNextScrollPosition([NotNullWhen(true)] out float? nextScrollPosition)
    {
        nextScrollPosition = null;

        var scroll = SupermattersTable.Parent as ScrollContainer;
        if (scroll == null)
            return false;

        var container = scroll.Children.ElementAt(0) as BoxContainer;
        if (container == null || !container.Children.Any())
            return false;

        if (!container.Children.Any(x => x.Height > 0))
            return false;

        nextScrollPosition = 0;

        foreach (var control in container.Children)
        {
            if (control is not SupermatterEntryContainer entry)
                continue;

            if (entry.NetEntity == _trackedEntity)
                return true;

            nextScrollPosition += control.Height;
        }

        nextScrollPosition = null;
        return false;
    }
}
