using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Backmen.Supermatter.Consoles;

[GenerateTypedNameReferences]
public sealed partial class SupermatterGasBarContainer : BoxContainer
{
    public SupermatterGasBarContainer()
    {
        RobustXamlLoader.Load(this);

        var cache = IoCManager.Resolve<IResourceCache>();
        var normalFont = new VectorFont(cache.GetResource<FontResource>("/Fonts/NotoSansDisplay/NotoSansDisplay-Regular.ttf"), 11);
        var monoFont = new VectorFont(cache.GetResource<FontResource>("/EngineFonts/NotoSans/NotoSansMono-Regular.ttf"), 10);

        GasLabel.FontOverride = normalFont;
        GasBarLabel.FontOverride = monoFont;
    }

    public void UpdateEntry(string name, Color color, float value)
    {
        GasBar.Value = value;
        GasLabel.Text = name + ":";
        GasBarLabel.Text = Loc.GetString("supermatter-console-window-label-gas-bar", ("gas", value.ToString("0.00")));

        GasBar.ForegroundStyleBoxOverride ??= new StyleBoxFlat();
        GasBarBorder.PanelOverride ??= new StyleBoxFlat();

        ((StyleBoxFlat) GasBar.ForegroundStyleBoxOverride).BackgroundColor = color;
        ((StyleBoxFlat) GasBarBorder.PanelOverride).BackgroundColor = color;
    }
}
