using System.Linq;
using System.Numerics;
using Content.Client.Atmos.EntitySystems;
using Content.Client.Stylesheets;
using Content.Shared.Atmos;
using Content.Shared.Atmos.Prototypes;
using Content.Shared.Backmen.Supermatter.Consoles;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.ResourceManagement;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Backmen.Supermatter.Consoles;

[GenerateTypedNameReferences]
public sealed partial class SupermatterEntryContainer : BoxContainer
{
    public NetEntity NetEntity;

    private readonly IEntityManager _entManager;
    private readonly Dictionary<string, EngineBarEntry> _engineDictionary;

    public SupermatterEntryContainer(NetEntity uid)
    {
        RobustXamlLoader.Load(this);

        _entManager = IoCManager.Resolve<IEntityManager>();
        var cache = IoCManager.Resolve<IResourceCache>();

        NetEntity = uid;

        var normalFont = new VectorFont(cache.GetResource<FontResource>("/Fonts/NotoSansDisplay/NotoSansDisplay-Regular.ttf"), 11);
        var monoFont = new VectorFont(cache.GetResource<FontResource>("/EngineFonts/NotoSans/NotoSansMono-Regular.ttf"), 10);

        IntegrityLabel.FontOverride = normalFont;
        PowerLabel.FontOverride = normalFont;
        RadiationLabel.FontOverride = normalFont;
        MolesLabel.FontOverride = normalFont;
        TemperatureLabel.FontOverride = normalFont;
        TemperatureLimitLabel.FontOverride = normalFont;
        WasteLabel.FontOverride = normalFont;
        AbsorptionLabel.FontOverride = normalFont;

        IntegrityBarLabel.FontOverride = monoFont;
        PowerBarLabel.FontOverride = monoFont;
        RadiationBarLabel.FontOverride = monoFont;
        MolesBarLabel.FontOverride = monoFont;
        TemperatureBarLabel.FontOverride = monoFont;
        TemperatureLimitBarLabel.FontOverride = monoFont;
        WasteBarLabel.FontOverride = monoFont;
        AbsorptionBarLabel.FontOverride = monoFont;

        var red = StyleNano.DangerousRedFore;
        var orange = StyleNano.ConcerningOrangeFore;
        var green = StyleNano.GoodGreenFore;
        var turqoise = Color.FromHex("#009893");

        _engineDictionary = new Dictionary<string, EngineBarEntry>
        {
            { "integrity", new EngineBarEntry(IntegrityBarLabel, IntegrityBar, IntegrityBarBorder, 0.9f, 0.1f, red, orange, green) },
            { "power", new EngineBarEntry(PowerBarLabel, PowerBar, PowerBarBorder, 0.9f, 0.1f, green, orange, red) },
            { "radiation", new EngineBarEntry(RadiationBarLabel, RadiationBar, RadiationBarBorder, 0.1f, 0.9f, green, orange, red) },
            { "moles", new EngineBarEntry(MolesBarLabel, MolesBar, MolesBarBorder, 0.5f, 0.5f, green, orange, red) },
            { "temperature", new EngineBarEntry(TemperatureBarLabel, TemperatureBar, TemperatureBarBorder, 0.5f, 0.5f, turqoise, green, red) },
            { "waste", new EngineBarEntry(WasteBarLabel, WasteBar, WasteBarBorder, 0.5f, 0.5f, green, orange, red) },
        };
    }

    public void UpdateEntry(SupermatterConsoleEntry entry, bool isFocus, SupermatterFocusData? focusData = null)
    {
        NetEntity = entry.NetEntity;

        SupermatterNameLabel.Text = Loc.GetString("supermatter-console-window-label-sm", ("name", entry.EntityName));
        FocusContainer.Visible = isFocus;

        if (!isFocus || focusData == null)
            return;

        _engineDictionary["integrity"].Value = focusData.Value.Integrity;
        _engineDictionary["power"].Value = focusData.Value.Power;
        _engineDictionary["radiation"].Value = focusData.Value.Radiation;
        _engineDictionary["moles"].Value = focusData.Value.AbsorbedMoles;
        _engineDictionary["temperature"].Value = focusData.Value.Temperature;
        _engineDictionary["waste"].Value = focusData.Value.WasteMultiplier;

        var powerBar = _engineDictionary["power"];
        var powerPrefix = powerBar.Value switch { >= 1000 => "G", >= 1 => "M", _ => "" };
        var powerMultiplier = powerBar.Value switch { >= 1000 => 0.001, >= 1 => 1, _ => 1000 };
        powerBar.Label.Text = Loc.GetString("supermatter-console-window-label-power-bar",
            ("power", (powerBar.Value * powerMultiplier).ToString("0.000")),
            ("prefix", powerPrefix));

        var temperatureLimit = focusData.Value.TemperatureLimit;
        TemperatureBar.MaxValue = Math.Max(temperatureLimit, 1f);
        TemperatureLimitBarLabel.Text = Loc.GetString("supermatter-console-window-label-temperature-bar",
            ("temperature", temperatureLimit.ToString("0.00")));

        AbsorptionBarLabel.Text = Loc.GetString("supermatter-console-window-label-absorption-bar",
            ("absorption", focusData.Value.AbsorptionRatio.ToString("0")));

        foreach (var bar in _engineDictionary)
        {
            var current = bar.Value;
            UpdateEngineBar(current.Bar, current.Border, current.Value, current.LeftSize, current.RightSize,
                current.LeftColor, current.MiddleColor, current.RightColor);

            if (bar.Key == "power")
                continue;

            current.Label.Text = Loc.GetString("supermatter-console-window-label-" + bar.Key + "-bar",
                (bar.Key, current.Value.ToString("0.00")));
        }

        var atmosphereSystem = _entManager.System<AtmosphereSystem>();
        var gases = focusData.Value.GasStorage.Keys
            .Select(atmosphereSystem.GetGas)
            .OrderByDescending(gas => GetStoredGas(gas, focusData));

        var index = 0;
        foreach (var gas in gases)
        {
            var stored = GetStoredGas(gas, focusData);
            var value = focusData.Value.AbsorbedMoles > 0f
                ? stored / focusData.Value.AbsorbedMoles * 100f
                : 0f;

            UpdateGasBar(index, GasTable, Loc.GetString(gas.Name), gas.Color, value);
            index++;
        }
    }

    /// <summary>
    /// Looks up stored moles using the gas prototype ID string (PR #6808), not a numeric index.
    /// </summary>
    private static float GetStoredGas(GasPrototype gas, SupermatterFocusData? focusData)
    {
        if (focusData is null)
            return 0f;

        if (!Enum.TryParse(gas.ID, out Gas id))
            return 0f;

        return focusData.Value.GasStorage.GetValueOrDefault(id);
    }

    private static void UpdateEngineBar(
        ProgressBar bar,
        PanelContainer border,
        float value,
        float leftSize,
        float rightSize,
        Color leftColor,
        Color middleColor,
        Color rightColor)
    {
        var clamped = Math.Clamp(value, bar.MinValue, bar.MaxValue);
        var normalized = clamped / Math.Max(bar.MaxValue, 1f);
        var leftHsv = Color.ToHsv(leftColor);
        var middleHsv = Color.ToHsv(middleColor);
        var rightHsv = Color.ToHsv(rightColor);

        var minColor = new Vector4(0, 0, 0, 0);
        var maxColor = new Vector4(1, 1, 1, 1);
        Color finalColor;

        if (normalized <= leftSize)
        {
            normalized /= leftSize;
            var calcColor = Vector4.Lerp(leftHsv, middleHsv, normalized);
            finalColor = Color.FromHsv(Vector4.Clamp(calcColor, minColor, maxColor));
        }
        else
        {
            normalized = (normalized - leftSize) / rightSize;
            var calcColor = Vector4.Lerp(middleHsv, rightHsv, normalized);
            finalColor = Color.FromHsv(Vector4.Clamp(calcColor, minColor, maxColor));
        }

        bar.ForegroundStyleBoxOverride ??= new StyleBoxFlat();
        border.PanelOverride ??= new StyleBoxFlat();

        ((StyleBoxFlat) bar.ForegroundStyleBoxOverride).BackgroundColor = finalColor;
        ((StyleBoxFlat) border.PanelOverride).BackgroundColor = finalColor;
        bar.Value = clamped;
    }

    private void UpdateGasBar(int index, Control table, string name, Color color, float value)
    {
        if (index >= table.ChildCount)
            table.AddChild(new SupermatterGasBarContainer());

        var tableChild = table.GetChild(index);

        if (tableChild is not SupermatterGasBarContainer)
        {
            table.RemoveChild(tableChild);
            UpdateGasBar(index, table, name, color, value);
            return;
        }

        ((SupermatterGasBarContainer) tableChild).UpdateEntry(name, color, value);
    }

    private sealed class EngineBarEntry
    {
        public readonly Label Label;
        public readonly ProgressBar Bar;
        public readonly PanelContainer Border;
        public float Value;
        public readonly float LeftSize;
        public readonly float RightSize;
        public readonly Color LeftColor;
        public readonly Color MiddleColor;
        public readonly Color RightColor;

        public EngineBarEntry(
            Label label,
            ProgressBar bar,
            PanelContainer border,
            float leftSize,
            float rightSize,
            Color leftColor,
            Color middleColor,
            Color rightColor)
        {
            Label = label;
            Bar = bar;
            Border = border;
            LeftSize = leftSize;
            RightSize = rightSize;
            LeftColor = leftColor;
            MiddleColor = middleColor;
            RightColor = rightColor;
        }
    }
}
