using Content.Shared.ADT.Mech;
using Content.Shared.Timing;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Timing;

namespace Content.Client.ADT.Mech.UI;

[GenerateTypedNameReferences]
public sealed partial class MechGunUiFragment : BoxContainer
{
    [Dependency] private readonly IGameTiming _timing = default!;

    public event Action<EntityUid?>? ReloadAction;
    public EntityUid? FragmentOwner;
    private StartEndTime _reloadTimer;
    public float ReloadTime = 10f;

    public MechGunUiFragment()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
    }

    protected override void FrameUpdate(FrameEventArgs args)
    {
        base.FrameUpdate(args);

        var curTime = _timing.CurTime;

        var progress = _reloadTimer.ProgressAt(curTime);

        ReloadButton.OnPressed += _ => ReloadAction?.Invoke(FragmentOwner);

        if (progress >= 1 && ReloadButton.Disabled)
            ReloadButton.Disabled = false;
    }
    public void UpdateContents(MechGunUiState state)
    {
        ReloadTime = state.ReloadTime;

        if (state.Reloading && state.ReloadEndTime != null)
        {
            _reloadTimer.End = state.ReloadEndTime.Value;
            _reloadTimer.Start = state.ReloadEndTime.Value - TimeSpan.FromSeconds(ReloadTime);
            ReloadButton.Disabled = true;
            return;
        }

        ShotsCount.Text = $"{state.Shots} / {state.Capacity}";
    }

    public void StartTimer()
    {
        var curTime = _timing.CurTime;
        _reloadTimer.Start = curTime;
        _reloadTimer.End = curTime + TimeSpan.FromSeconds(ReloadTime);
        ReloadButton.Disabled = true;
    }
}
