using Content.Shared.Backmen.Economy.Eftpos;
using Content.Shared.FixedPoint;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Backmen.Economy.Eftpos.UI;

    [GenerateTypedNameReferences]
    public sealed partial class EftposMenu : DefaultWindow
    {
        public event Action<LineEdit.LineEditEventArgs, FixedPoint2?>? OnChangeValue;
        public event Action<BaseButton.ButtonEventArgs>? OnResetValue;
        public event Action<LineEdit.LineEditEventArgs, string?>? OnChangeLinkedAccount;
        public event Action<BaseButton.ButtonEventArgs>? OnResetLinkedAccount;
        public event Action<BaseButton.ButtonEventArgs>? OnSwipeCard;
        public event Action<BaseButton.ButtonEventArgs>? OnLock;
        public EftposMenu()
        {
            RobustXamlLoader.Load(this);
            ValueLineEdit.OnTextEntered += OnValueLineEditTextEntered;
            ValueButton.OnButtonDown += OnValueButtonButtonDown;
            LinkedAccountLineEdit.OnTextEntered += OnLinkedAccountLineEditTextEntered;
            LinkedAccountButton.OnButtonDown += OnLinkedAccounButtonButtonDown;
            SwipeCardButton.OnButtonDown += OnSwipeCardButtonButtonDown;
            LockButton.OnButtonDown += OnLockButtonButtonDown;
        }
        public void UpdateState(SharedEftposComponent.EftposBoundUserInterfaceState state)
        {
            UpdateValue(state.Value);
            UpdateLinkedAccount(state.LinkedAccountNumber, state.LinkedAccountName);
            UpdateLocked(state.IsLocked);
            SymbolLabel.Text = state.CurrencySymbol ?? "";
        }

        private void OnValueLineEditTextEntered(LineEdit.LineEditEventArgs args)
        {
            if (TryGetValueFromValueLineEdit(out var value))
                OnChangeValue?.Invoke(args, value);
        }
        private void OnValueButtonButtonDown(BaseButton.ButtonEventArgs args)
        {
            OnResetValue?.Invoke(args);
        }
        private void OnLinkedAccountLineEditTextEntered(LineEdit.LineEditEventArgs args)
        {
            OnChangeLinkedAccount?.Invoke(args, LinkedAccountLineEdit.Text);
        }
        private void OnLinkedAccounButtonButtonDown(BaseButton.ButtonEventArgs args)
        {
            OnResetLinkedAccount?.Invoke(args);
        }
        private void OnSwipeCardButtonButtonDown(BaseButton.ButtonEventArgs args)
        {
            OnSwipeCard?.Invoke(args);
        }
        private void OnLockButtonButtonDown(BaseButton.ButtonEventArgs args)
        {
            OnLock?.Invoke(args);
        }
        private bool TryGetValueFromValueLineEdit(out FixedPoint2 value)
        {
            value = 0;
            if(int.TryParse(ValueLineEdit.Text, out int result))
            {
                value = FixedPoint2.New(result);
                return true;
            }
            ValueLineEdit.Clear();
            return false;
        }
        private void UpdateLinkedAccount(string? linkedAccountNumber, string? linkedAccountName)
        {
            bool isValid = linkedAccountNumber != null;
            LinkedAccountLineEdit.Visible = !isValid;
            SymbolLabel.Visible = LinkedAccountButton.Visible = isValid;
            if (isValid)
            {
                string s = string.Empty;
                if (linkedAccountName != null) s = $"{linkedAccountName} ";
                LinkedAccountButton.Text = s + $"#{linkedAccountNumber}";
            }
        }
        private void UpdateValue(FixedPoint2? value)
        {
            bool isValid = value != null;
            ValueLineEdit.Visible = !isValid;
            ValueButton.Visible = isValid;
            if (isValid)
            {
                ValueButton.Text = value.ToString();
            }
        }
        private void UpdateLocked(bool isLocked)
        {
            SwipeCardButton.Visible = LockButton.Disabled = isLocked;
            SwipeCardButton.Disabled = LockButton.Visible = !isLocked;
            //ValueButton.Disabled = LinkedAccountButton.Disabled = isLocked;
        }
    }
