using Content.Shared.Backmen.Reinforcement;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Backmen.Reinforcement.UI;

[GenerateTypedNameReferences]
public sealed partial class ActiveReinforcementRow : PanelContainer
{
    public uint Id { get; set; }
    public ReinforcementPrototype? Model { get; set; }
    public NetEntity Owner { get; set; } = NetEntity.Invalid;
    public string OwnerName { get; set; } = "";

    public ActiveReinforcementRow()
    {
        RobustXamlLoader.Load(this);
    }
}
