using Content.Shared.Backmen.Reinforcement;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.Backmen.Reinforcement.UI;

[GenerateTypedNameReferences]
public sealed partial class ReinforcementRow : PanelContainer
{
    public uint Id { get; set; }
    public ReinforcementPrototype? Model { get; set; }
    public int ModelCount { get; set; }

    public ReinforcementRow()
    {
        RobustXamlLoader.Load(this);
    }
}
