using System.Numerics;
using Content.Shared.Backmen.Surgery.Traumas.Systems;
using Content.Shared.Backmen.Surgery.Wounds;
using Content.Shared.Backmen.Surgery.Wounds.Systems;
using Content.Shared.Backmen.Targeting;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client.Backmen.Medical.UI;

[GenerateTypedNameReferences]
public sealed partial class DollViewDisplay : Control
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private readonly SpriteSystem _spriteSystem;

    // Start-backmen: surgery
    public event Action<TargetBodyPart?, EntityUid>? OnBodyPartSelected;
    private EntityUid _spriteViewEntity;

    private readonly EntProtoId _bodyView = "AlertSpriteView";

    private readonly Dictionary<TargetBodyPart, TextureButton> _bodyPartControls;
    private EntityUid? _target;

    // End-backmen: surgery

    public DollViewDisplay()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this); // backmen

        _spriteSystem = _entityManager.System<SpriteSystem>();
        // Start-backmen: surgery
        _bodyPartControls = new Dictionary<TargetBodyPart, TextureButton>
        {
            { TargetBodyPart.Head, HeadButton },
            { TargetBodyPart.Chest, ChestButton }, // backmen: cheat, groin separation
            { TargetBodyPart.Groin, GroinButton },
            { TargetBodyPart.LeftArm, LeftArmButton },
            { TargetBodyPart.LeftHand, LeftHandButton },
            { TargetBodyPart.RightArm, RightArmButton },
            { TargetBodyPart.RightHand, RightHandButton },
            { TargetBodyPart.LeftLeg, LeftLegButton },
            { TargetBodyPart.LeftFoot, LeftFootButton },
            { TargetBodyPart.RightLeg, RightLegButton },
            { TargetBodyPart.RightFoot, RightFootButton },
        };

        foreach (var bodyPartButton in _bodyPartControls)
        {
            bodyPartButton.Value.MouseFilter = MouseFilterMode.Stop;
            bodyPartButton.Value.OnPressed += _ => SetActiveBodyPart(bodyPartButton.Key, bodyPartButton.Value);
        }
        //ReturnButton.OnPressed += _ => ResetBodyPart();
        // End-backmen: surgery
    }

    public void SetActiveBodyPart(TargetBodyPart part, TextureButton button)
    {
        if (_target == null)
            return;

        OnBodyPartSelected?.Invoke(part, _target.Value);
    }

    public void ResetBodyPart()
    {
        if (_target == null)
            return;

        OnBodyPartSelected?.Invoke(null, _target.Value);
    }

    public void SetActiveButtons(bool isHumanoid)
    {
        foreach (var button in _bodyPartControls)
            button.Value.Visible = isHumanoid;
    }

    // Start-backmen: surgery
    /// <summary>
    /// Sets up the Body Doll using Alert Entity to use in Health Analyzer.
    /// </summary>
    public EntityUid? SetupIcon(Dictionary<TargetBodyPart, WoundableSeverity>? body)
    {
        if (body is null)
            return null;

        if (!_entityManager.Deleted(_spriteViewEntity))
            _entityManager.QueueDeleteEntity(_spriteViewEntity);

        _spriteViewEntity = _entityManager.Spawn(_bodyView);

        if (!_entityManager.TryGetComponent<SpriteComponent>(_spriteViewEntity, out var sprite))
            return null;

        int layer = 0;
        foreach (var (bodyPart, integrity) in body)
        {
            // TODO: Fix this way PartStatusUIController and make it use layers instead of TextureRects
            string enumName = Enum.GetName(typeof(TargetBodyPart), bodyPart) ?? "Unknown";
            int enumValue = (int) integrity;
            var rsi = new SpriteSpecifier.Rsi(new ResPath($"/Textures/Interface/Targeting/Status/{enumName.ToLowerInvariant()}.rsi"), $"{enumName.ToLowerInvariant()}_{enumValue}");
            // It's probably shitcode but im lazy to get into sprite stuff - It is shitcode :)
            if (!sprite.TryGetLayer(layer, out _))
                sprite.AddLayer(_spriteSystem.Frame0(rsi));
            else
                sprite.LayerSetTexture(layer, _spriteSystem.Frame0(rsi));
            sprite.LayerSetScale(layer, new Vector2(3f, 3f));
            layer++;
        }
        return _spriteViewEntity;
    }
    // End-backmen: surgery
}
