using System.Linq;
using Content.Client.Message;
using Content.Client.UserInterface.Systems.Guidebook;
using Content.Shared.Backmen.Surgery.Consciousness;
using Content.Shared.Backmen.Surgery.Consciousness.Systems;
using Content.Shared.Guidebook;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.IoC;
using Robust.Shared.Localization;
using Robust.Shared.Maths;
using Robust.Shared.Prototypes;

namespace Content.Client.Backmen.Medical.UI;

[GenerateTypedNameReferences]
public sealed partial class PainCausesDisplay : Control
{
    private const float DefaultMaxPainValue = 250f;
    private const float DefaultCriticalThreshold = 200f;
    private const float DefaultMediumThreshold = 100f;

    private float _maxPainValue = DefaultMaxPainValue;
    private float _criticalThreshold = DefaultCriticalThreshold;
    private float _mediumThreshold = DefaultMediumThreshold;

    [Dependency] private IEntityManager _entManager = default!;
    [Dependency] private IUserInterfaceManager _uiManager = default!;
    private readonly ConsciousnessSystem _consciousness;

    public PainCausesDisplay()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _consciousness = _entManager.System<ConsciousnessSystem>();
    }

    public void UpdatePainCauses(Dictionary<string, float>? painCauses, float? totalPain = null, EntityUid? target = null)
    {
        RootContainer.RemoveAllChildren();

        float? painCap = null;
        float? softPainCap = null;
        if (target.HasValue)
        {
            var nerveSys = _consciousness.GetNerveSystem(target.Value);
            if (nerveSys.HasValue)
            {
                painCap = (float) nerveSys.Value.Comp.PainCap;
                softPainCap = (float) nerveSys.Value.Comp.SoftPainCap;
            }
        }

        _maxPainValue = painCap ?? DefaultMaxPainValue;
        _mediumThreshold = softPainCap ?? DefaultMediumThreshold;
        _criticalThreshold = painCap.HasValue && softPainCap.HasValue
            ? (softPainCap.Value + painCap.Value) / 2f
            : DefaultCriticalThreshold;

        if ((painCauses == null || painCauses.Count == 0) && totalPain == null)
        {
            Visible = false;
            return;
        }

        Visible = true;

        var hasNerveSystemPain = totalPain.HasValue;
        var hasBodyPainCauses = painCauses is { Count: > 0 };
        var addedNerveSection = false;

        if (hasNerveSystemPain)
        {
            RootContainer.AddChild(CreateNerveSystemPainSection(totalPain!.Value));
            addedNerveSection = true;
        }

        if (hasBodyPainCauses && addedNerveSection)
            RootContainer.AddChild(CreateSectionDivider());

        if (hasBodyPainCauses)
        {
            var causes = painCauses!;
            var totalPainFromCauses = causes.Values.Sum();
            RootContainer.AddChild(CreateTotalPainFromCausesSection(totalPainFromCauses));
            RootContainer.AddChild(CreateSectionDivider());

            var painCausesSorted = causes
                .OrderByDescending(p => p.Value)
                .ToDictionary(x => x.Key, x => x.Value);

            var allGuideIds = painCausesSorted.Keys
                .Select(GetTreatmentGuideId)
                .Where(id => id != null)
                .Cast<ProtoId<GuideEntryPrototype>>()
                .Distinct()
                .ToList();

            var showSingleHelpButton = allGuideIds.Count == 1;

            foreach (var (identifier, value) in painCausesSorted)
                RootContainer.AddChild(CreatePainCauseSection(identifier, value, showSingleHelpButton));

            if (showSingleHelpButton)
                RootContainer.AddChild(CreateHelpButton(allGuideIds[0]));
        }
    }

    private static PanelContainer CreateSectionDivider()
    {
        return new PanelContainer
        {
            StyleClasses = { "LowDivider" },
            Margin = new Thickness(0, 5),
        };
    }

    private BoxContainer CreateNerveSystemPainSection(float totalPain)
    {
        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(0, 5, 0, 10),
        };

        var labelRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        labelRow.AddChild(new Label
        {
            Text = Loc.GetString("health-analyzer-window-nerve-system-pain-text"),
            HorizontalExpand = true,
        });

        var statusLabel = new RichTextLabel { Margin = new Thickness(5, 0, 5, 0) };
        statusLabel.SetMarkup(GetPainStatusText(totalPain));
        labelRow.AddChild(statusLabel);

        labelRow.AddChild(new Label
        {
            Text = $"{totalPain:F1}",
            HorizontalAlignment = HAlignment.Right,
        });

        container.AddChild(labelRow);
        container.AddChild(CreatePainBar(totalPain, 25));
        return container;
    }

    private BoxContainer CreateTotalPainFromCausesSection(float totalPainFromCauses)
    {
        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(0, 5, 0, 10),
        };

        var labelRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        labelRow.AddChild(new Label
        {
            Text = Loc.GetString("health-analyzer-window-total-pain-from-causes-text"),
            HorizontalExpand = true,
        });

        labelRow.AddChild(new Label
        {
            Text = $"{totalPainFromCauses:F1}",
            HorizontalAlignment = HAlignment.Right,
        });

        container.AddChild(labelRow);
        container.AddChild(CreatePainBar(totalPainFromCauses, 25));
        return container;
    }

    private BoxContainer CreatePainCauseSection(string identifier, float value, bool showPerCauseHelp)
    {
        var container = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(0, 5, 0, 5),
        };

        var labelRow = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
            HorizontalExpand = true,
        };

        labelRow.AddChild(new Label
        {
            Text = GetPainCauseName(identifier),
            HorizontalExpand = true,
        });

        labelRow.AddChild(new Label
        {
            Text = $"{value:F1}",
            HorizontalAlignment = HAlignment.Right,
        });

        container.AddChild(labelRow);
        container.AddChild(CreatePainBar(value, 20));

        if (!showPerCauseHelp)
        {
            var helpGuideId = GetTreatmentGuideId(identifier);
            if (helpGuideId != null)
                container.AddChild(CreateHelpButton(helpGuideId.Value, new Thickness(10, 4, 0, 0)));
        }

        return container;
    }

    private Button CreateHelpButton(ProtoId<GuideEntryPrototype> guideId, Thickness? margin = null)
    {
        var helpButton = new Button
        {
            Text = Loc.GetString("health-analyzer-window-pain-help-button"),
            Margin = margin ?? new Thickness(0, 10, 0, 0),
            HorizontalAlignment = HAlignment.Left,
        };

        helpButton.OnPressed += _ =>
        {
            var guidebookController = _uiManager.GetUIController<GuidebookUIController>();
            guidebookController.OpenGuidebook(
                new List<ProtoId<GuideEntryPrototype>> { "Medical" },
                selected: guideId);
        };

        return helpButton;
    }

    private ProgressBar CreatePainBar(float value, int height)
    {
        var bar = new ProgressBar
        {
            MinValue = 0,
            MaxValue = _maxPainValue,
            Value = Math.Min(value, _maxPainValue),
            HorizontalExpand = true,
            SetHeight = height,
            Margin = new Thickness(0, 2, 0, 0),
        };

        bar.ForegroundStyleBoxOverride = new StyleBoxFlat
        {
            BackgroundColor = GetPainColor(value),
        };

        return bar;
    }

    private static string GetPainCauseName(string identifier)
    {
        return identifier switch
        {
            "WoundPain" => Loc.GetString("health-analyzer-window-pain-cause-wound-pain"),
            ConsciousnessModifierIds.Asphyxiation => Loc.GetString("health-analyzer-window-pain-cause-suffocation"),
            "Bloodloss" => Loc.GetString("health-analyzer-window-pain-cause-bloodloss"),
            "DeathThreshold" => Loc.GetString("health-analyzer-window-pain-cause-death-threshold"),
            "Suicide" => Loc.GetString("health-analyzer-window-pain-cause-suicide"),
            "OrganDamage" => Loc.GetString("health-analyzer-window-pain-cause-organ-damage"),
            _ => identifier,
        };
    }

    private ProtoId<GuideEntryPrototype>? GetTreatmentGuideId(string identifier)
    {
        return identifier switch
        {
            "WoundPain" => "MedicalDoctor",
            ConsciousnessModifierIds.Asphyxiation => "MedicalDoctor",
            "Bloodloss" => "MedicalDoctor",
            "DeathThreshold" => "MedicalDoctor",
            "Suicide" => "MedicalDoctor",
            "OrganDamage" => "MedicalDoctor",
            _ => null,
        };
    }

    private string GetPainStatusText(float value)
    {
        if (value >= _maxPainValue)
            return Loc.GetString("health-analyzer-window-pain-status-fatal");
        if (value >= _criticalThreshold)
            return Loc.GetString("health-analyzer-window-pain-status-critical");
        if (value >= _mediumThreshold)
            return Loc.GetString("health-analyzer-window-pain-status-moderate");
        if (value > 0)
            return Loc.GetString("health-analyzer-window-pain-status-low");

        return Loc.GetString("health-analyzer-window-pain-status-none");
    }

    private Color GetPainColor(float value)
    {
        if (value >= _maxPainValue)
            return new Color(0.3f, 0f, 0f, 1f);

        if (value >= _criticalThreshold)
        {
            var ratio = (value - _criticalThreshold) / (_maxPainValue - _criticalThreshold);
            return Color.InterpolateBetween(new Color(1f, 0f, 0f, 1f), new Color(0.5f, 0f, 0f, 1f), ratio);
        }

        if (value >= _mediumThreshold)
        {
            var ratio = (value - _mediumThreshold) / (_criticalThreshold - _mediumThreshold);
            return Color.InterpolateBetween(new Color(1f, 1f, 0f, 1f), new Color(1f, 0f, 0f, 1f), ratio);
        }

        var lowRatio = value / _mediumThreshold;
        return Color.InterpolateBetween(new Color(0f, 1f, 0f, 1f), new Color(1f, 1f, 0f, 1f), lowRatio);
    }
}
