using System.Linq;
using Content.Client.Message;
using Content.Client.UserInterface.Systems.Guidebook; // backmen
using Content.Shared.Backmen.Surgery.Consciousness.Systems; // backmen
using Content.Shared.Backmen.Surgery.Pain.Components; // backmen
using Content.Shared.Guidebook; // backmen
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Shared.IoC;
using Robust.Shared.Maths;
using Robust.Shared.Localization;
using Robust.Shared.Prototypes; // backmen

namespace Content.Client.Backmen.Medical.UI;

[GenerateTypedNameReferences]
public sealed partial class PainCausesDisplay : Control
{
    // Default values if not provided from server
    private const float DefaultMaxPainValue = 250f;
    private const float DefaultCriticalThreshold = 200f;
    private const float DefaultMediumThreshold = 100f;

    private float _maxPainValue = DefaultMaxPainValue;
    private float _criticalThreshold = DefaultCriticalThreshold;
    private float _mediumThreshold = DefaultMediumThreshold;

    [Dependency] private readonly IEntityManager _entManager = default!; // backmen
    [Dependency] private readonly IUserInterfaceManager _uiManager = default!; // backmen
    [Dependency] private readonly IPrototypeManager _prototypeManager = default!; // backmen
    private readonly ConsciousnessSystem _consciousness; // backmen

    public PainCausesDisplay()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this); // backmen
        _consciousness = _entManager.System<ConsciousnessSystem>();
    }

    public void UpdatePainCauses(Dictionary<string, float>? painCauses, float? totalPain = null, EntityUid? target = null)
    {
        // Start-backmen: clear tab contents
        NerveSystemTab.RemoveAllChildren();
        BodyPainCausesTab.RemoveAllChildren();
        
        // Also clear RootContainer if we're not using tabs (for direct content display)
        // We'll check if tabs are visible later and clear RootContainer if needed
        // End-backmen: clear tab contents

        // Start-backmen: use PainCap and SoftPainCap from NerveSystemComponent
        // Get NerveSystemComponent through ConsciousnessComponent (nerve system is in the brain, not the body)
        float? painCap = null;
        float? softPainCap = null;
        if (target.HasValue)
        {
            var nerveSys = _consciousness.GetNerveSystem(target.Value);
            if (nerveSys.HasValue)
            {
                painCap = (float)nerveSys.Value.Comp.PainCap;
                softPainCap = (float)nerveSys.Value.Comp.SoftPainCap;
            }
        }

        _maxPainValue = painCap ?? DefaultMaxPainValue;
        _mediumThreshold = softPainCap ?? DefaultMediumThreshold; // SoftPainCap is the pain crit threshold
        // Critical threshold is between SoftPainCap and PainCap
        _criticalThreshold = (painCap.HasValue && softPainCap.HasValue)
            ? (softPainCap.Value + painCap.Value) / 2f
            : DefaultCriticalThreshold;
        // End-backmen: use PainCap and SoftPainCap

        if ((painCauses == null || painCauses.Count == 0) && totalPain == null)
        {
            Visible = false;
            return;
        }

        Visible = true;

        // Start-backmen: setup tabs
        var hasNerveSystemPain = totalPain.HasValue;
        var hasBodyPainCauses = painCauses != null && painCauses.Count > 0;

        // Show tabs only if we have both types of data, otherwise show directly in RootContainer
        if (hasNerveSystemPain && hasBodyPainCauses)
        {
            PainTabs.Visible = true;
            PainTabs.SetTabTitle(0, Loc.GetString("health-analyzer-window-tab-nerve-system-pain"));
            PainTabs.SetTabTitle(1, Loc.GetString("health-analyzer-window-tab-body-pain-causes"));
            // Clear RootContainer from direct children (when using tabs, content goes into tabs, not RootContainer)
            var directChildren = RootContainer.Children.Where(c => c != PainTabs).ToList();
            foreach (var child in directChildren)
            {
                RootContainer.RemoveChild(child);
            }
        }
        else
        {
            PainTabs.Visible = false;
            // Clear RootContainer from direct children (when not using tabs, we'll add content directly)
            // But keep PainTabs in the tree (it's part of XAML structure)
            var directChildren = RootContainer.Children.Where(c => c != PainTabs).ToList();
            foreach (var child in directChildren)
            {
                RootContainer.RemoveChild(child);
            }
        }
        // End-backmen: setup tabs

        // Start-backmen: nerve system pain
        if (totalPain.HasValue)
        {
            var nerveSystemPainContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(0, 5, 0, 10),
            };

            var nerveSystemPainLabelContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            var nerveSystemPainLabel = new Label
            {
                Text = Loc.GetString("health-analyzer-window-nerve-system-pain-text"),
                HorizontalExpand = true,
            };
            nerveSystemPainLabelContainer.AddChild(nerveSystemPainLabel);

            var nerveSystemPainStatusLabel = new RichTextLabel
            {
                Margin = new Thickness(5, 0, 5, 0),
            };
            nerveSystemPainStatusLabel.SetMarkup(GetPainStatusText(totalPain.Value));
            nerveSystemPainLabelContainer.AddChild(nerveSystemPainStatusLabel);

            var nerveSystemPainValueLabel = new Label
            {
                Text = $"{totalPain.Value:F1}",
                HorizontalAlignment = Control.HAlignment.Right,
            };
            nerveSystemPainLabelContainer.AddChild(nerveSystemPainValueLabel);

            nerveSystemPainContainer.AddChild(nerveSystemPainLabelContainer);

            var nerveSystemPainBar = new ProgressBar
            {
                MinValue = 0,
                MaxValue = _maxPainValue,
                Value = Math.Min(totalPain.Value, _maxPainValue),
                HorizontalExpand = true,
                SetHeight = 25,
                Margin = new Thickness(0, 2, 0, 0),
            };

            nerveSystemPainBar.ForegroundStyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = GetPainColor(totalPain.Value)
            };

            nerveSystemPainContainer.AddChild(nerveSystemPainBar);

            if (PainTabs.Visible)
            {
                NerveSystemTab.AddChild(nerveSystemPainContainer);
            }
            else
            {
                RootContainer.AddChild(nerveSystemPainContainer);
            }
        }
        // End-backmen: nerve system pain

        // Start-backmen: total pain from all causes
        if (painCauses != null && painCauses.Count > 0)
        {
            var totalPainFromCauses = painCauses.Values.Sum();
            var totalPainFromCausesContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(0, 5, 0, 10),
            };

            var totalPainFromCausesLabelContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            var totalPainFromCausesLabel = new Label
            {
                Text = Loc.GetString("health-analyzer-window-total-pain-from-causes-text"),
                HorizontalExpand = true,
            };
            totalPainFromCausesLabelContainer.AddChild(totalPainFromCausesLabel);

            var totalPainFromCausesValueLabel = new Label
            {
                Text = $"{totalPainFromCauses:F1}",
                HorizontalAlignment = Control.HAlignment.Right,
            };
            totalPainFromCausesLabelContainer.AddChild(totalPainFromCausesValueLabel);

            totalPainFromCausesContainer.AddChild(totalPainFromCausesLabelContainer);

            var totalPainFromCausesBar = new ProgressBar
            {
                MinValue = 0,
                MaxValue = _maxPainValue,
                Value = Math.Min(totalPainFromCauses, _maxPainValue),
                HorizontalExpand = true,
                SetHeight = 25,
                Margin = new Thickness(0, 2, 0, 0),
            };

            totalPainFromCausesBar.ForegroundStyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = GetPainColor(totalPainFromCauses)
            };

            totalPainFromCausesContainer.AddChild(totalPainFromCausesBar);

            if (PainTabs.Visible)
            {
                BodyPainCausesTab.AddChild(totalPainFromCausesContainer);
            }
            else
            {
                RootContainer.AddChild(totalPainFromCausesContainer);
            }
        }
        // End-backmen: total pain from all causes

        painCauses ??= [];


        var painCausesSorted = painCauses
            .OrderByDescending(p => p.Value)
            .ToDictionary(x => x.Key, x => x.Value);

        // Start-backmen: check if all pain causes have the same guide ID
        var allGuideIds = painCausesSorted.Keys
            .Select(GetTreatmentGuideId)
            .Where(id => id != null)
            .Distinct()
            .ToList();

        var showSingleHelpButton = allGuideIds.Count == 1 && allGuideIds[0] != null;
        // End-backmen: check if all pain causes have the same guide ID

        foreach (var (identifier, value) in painCausesSorted)
        {
            var painCauseContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Vertical,
                Margin = new Thickness(0, 5, 0, 5),
            };

            var labelContainer = new BoxContainer
            {
                Orientation = BoxContainer.LayoutOrientation.Horizontal,
                HorizontalExpand = true,
            };

            var painCauseLabel = new Label
            {
                Text = GetPainCauseName(identifier),
                HorizontalExpand = true,
            };
            labelContainer.AddChild(painCauseLabel);

            var valueLabel = new Label
            {
                Text = $"{value:F1}",
                HorizontalAlignment = Control.HAlignment.Right,
            };
            labelContainer.AddChild(valueLabel);

            painCauseContainer.AddChild(labelContainer);

            var painBar = new ProgressBar
            {
                MinValue = 0,
                MaxValue = _maxPainValue,
                Value = Math.Min(value, _maxPainValue),
                HorizontalExpand = true,
                SetHeight = 20,
                Margin = new Thickness(0, 2, 0, 0),
            };

            // Set color based on pain level
            painBar.ForegroundStyleBoxOverride = new StyleBoxFlat
            {
                BackgroundColor = GetPainColor(value)
            };

            painCauseContainer.AddChild(painBar);

            // Start-backmen: treatment help button (only show if not all have the same guide)
            if (!showSingleHelpButton)
            {
                var helpGuideId = GetTreatmentGuideId(identifier);
                if (helpGuideId != null)
                {
                    var helpButton = new Button
                    {
                        Text = Loc.GetString("health-analyzer-window-pain-help-button"),
                        Margin = new Thickness(10, 4, 0, 0),
                        HorizontalAlignment = Control.HAlignment.Left,
                    };
                    helpButton.OnPressed += _ =>
                    {
                        var guidebookController = _uiManager.GetUIController<GuidebookUIController>();
                        guidebookController.OpenGuidebook(
                            new List<ProtoId<GuideEntryPrototype>> { "Medical" },
                            selected: helpGuideId);
                    };
                    painCauseContainer.AddChild(helpButton);
                }
            }
            // End-backmen: treatment help button

            if (PainTabs.Visible)
            {
                BodyPainCausesTab.AddChild(painCauseContainer);
            }
            else
            {
                RootContainer.AddChild(painCauseContainer);
            }
        }

        // Start-backmen: add single help button if all causes have the same guide
        if (showSingleHelpButton && allGuideIds[0] != null)
        {
            var helpButton = new Button
            {
                Text = Loc.GetString("health-analyzer-window-pain-help-button"),
                Margin = new Thickness(0, 10, 0, 0),
                HorizontalAlignment = Control.HAlignment.Left,
            };
            helpButton.OnPressed += _ =>
            {
                var guidebookController = _uiManager.GetUIController<GuidebookUIController>();
                guidebookController.OpenGuidebook(
                    new List<ProtoId<GuideEntryPrototype>> { "Medical" },
                    selected: allGuideIds[0]);
            };
            if (PainTabs.Visible)
            {
                BodyPainCausesTab.AddChild(helpButton);
            }
            else
            {
                RootContainer.AddChild(helpButton);
            }
        }
        // End-backmen: add single help button
    }

    private static string GetPainCauseName(string identifier)
    {
        return identifier switch
        {
            "WoundPain" => Loc.GetString("health-analyzer-window-pain-cause-wound-pain"),
            "Suffocation" => Loc.GetString("health-analyzer-window-pain-cause-suffocation"),
            "Bloodloss" => Loc.GetString("health-analyzer-window-pain-cause-bloodloss"),
            "DeathThreshold" => Loc.GetString("health-analyzer-window-pain-cause-death-threshold"),
            "Suicide" => Loc.GetString("health-analyzer-window-pain-cause-suicide"),
            _ => identifier, // Fallback to identifier if no localization found
        };
    }

    // Start-backmen: treatment help
    /// <summary>
    /// Gets the guidebook entry ID for treatment information based on pain cause identifier.
    /// </summary>
    private ProtoId<GuideEntryPrototype>? GetTreatmentGuideId(string identifier)
    {
        return identifier switch
        {
            "WoundPain" => "MedicalDoctor",
            "Suffocation" => "MedicalDoctor",
            "Bloodloss" => "MedicalDoctor",
            "DeathThreshold" => "MedicalDoctor",
            "Suicide" => "MedicalDoctor",
            _ => null,
        };
    }

    /// <summary>
    /// Gets pain status text based on total pain value.
    /// </summary>
    private string GetPainStatusText(float value)
    {
        if (value >= _maxPainValue)
            return Loc.GetString("health-analyzer-window-pain-status-fatal");
        else if (value >= _criticalThreshold)
            return Loc.GetString("health-analyzer-window-pain-status-critical");
        else if (value >= _mediumThreshold)
            return Loc.GetString("health-analyzer-window-pain-status-moderate");
        else if (value > 0)
            return Loc.GetString("health-analyzer-window-pain-status-low");
        else
            return Loc.GetString("health-analyzer-window-pain-status-none");
    }

    // End-backmen: treatment help

    /// <summary>
    /// Gets the color for a pain bar based on the pain value.
    /// Uses PainCap and SoftPainCap from NerveSystemComponent for dynamic thresholds.
    /// </summary>
    private Color GetPainColor(float value)
    {
        if (value >= _maxPainValue)
        {
            // Death threshold - dark red/black
            return new Color(0.3f, 0f, 0f, 1f);
        }
        else if (value >= _criticalThreshold)
        {
            // Critical - red to dark red
            var ratio = (value - _criticalThreshold) / (_maxPainValue - _criticalThreshold);
            return Color.InterpolateBetween(new Color(1f, 0f, 0f, 1f), new Color(0.5f, 0f, 0f, 1f), ratio);
        }
        else if (value >= _mediumThreshold)
        {
            // Medium - yellow to orange to red
            var ratio = (value - _mediumThreshold) / (_criticalThreshold - _mediumThreshold);
            return Color.InterpolateBetween(new Color(1f, 1f, 0f, 1f), new Color(1f, 0f, 0f, 1f), ratio);
        }
        else
        {
            // Low - green to yellow
            var ratio = value / _mediumThreshold;
            return Color.InterpolateBetween(new Color(0f, 1f, 0f, 1f), new Color(1f, 1f, 0f, 1f), ratio);
        }
    }
}
