using System.Linq;
using System.Numerics;
using Content.Shared.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Content.Shared.Backmen.Antag;
using Content.Shared.Roles;
using Robust.Shared.Prototypes;

namespace Content.Client.UserInterface.Systems.Ghost.Controls
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostTargetWindow : DefaultWindow
    {
        [Dependency] private readonly IPrototypeManager _prototypeManager = default!;

        private List<GhostWarpPlayer> _playerWarps = new();
        private List<GhostWarpPlace> _placeWarps = new();
        private List<GhostWarpGlobalAntagonist> _globalAntagonists = new();

        private List<GhostWarpPlayer> _alivePlayers = new();
        private List<GhostWarpPlayer> _leftPlayers = new();
        private List<GhostWarpPlayer> _deadPlayers = new();
        private List<GhostWarpPlayer> _ghostPlayers = new();

        public event Action<NetEntity>? WarpClicked;

        public GhostTargetWindow()
        {
            IoCManager.InjectDependencies(this);
            RobustXamlLoader.Load(this);
        }

        public void Populate()
        {
            GhostTeleportContainer.DisposeAllChildren();

            PlayersAllocation();

            _playerWarps = GetSortedPlayers(_playerWarps);
            _placeWarps = GetSortedPlaces(_placeWarps);
            _globalAntagonists = GetSortedAntagonists(_globalAntagonists);

            AddButtons();
        }

        public void UpdateWarps(List<GhostWarpPlayer> players, List<GhostWarpPlace> places, List<GhostWarpGlobalAntagonist> antagonists)
        {
            _playerWarps = players;
            _placeWarps = places;
            _globalAntagonists = antagonists;
        }

        private void AddButtons()
        {
            AddAntagButtons(_globalAntagonists, "ghost-teleport-menu-antagonists-label", "ButtonColorAntagonistDepartment");
            AddPlayerButtons(_alivePlayers, "ghost-teleport-menu-alive-label", string.Empty, true); // Alive
            AddPlayerButtons(_deadPlayers, "ghost-teleport-menu-dead-label", string.Empty, true); // Dead
            AddPlayerButtons(_ghostPlayers, "ghost-teleport-menu-ghosts-label", string.Empty, true); // Ghost
            AddPlayerButtons(_leftPlayers, "ghost-teleport-menu-left-label", string.Empty, true); // Left
            AddPlaceButtons(_placeWarps, "ghost-teleport-menu-locations-label", "ButtonColorSpecificDepartment");
        }

        private void AddPlayerButtons(List<GhostWarpPlayer> players, string text, string styleClass,
            bool enableByDepartmentColorSheet)
        {
            if (players.Count == 0)
                return;

            var bigGrid = new GridContainer();

            var bigLabel = new Label
            {
                Text = Loc.GetString(text),
                StyleClasses = { "LabelBig" }
            };
            bigGrid.AddChild(bigLabel);

            var sortedPlayers = SortPlayersByDepartment(players);

            foreach (var departmentList in sortedPlayers)
            {
                if (departmentList.Count == 0)
                    continue;

                var departmentGrid = new GridContainer
                {
                    Columns = 5
                };

                var departmentPrototype = _prototypeManager.Index<DepartmentPrototype>(departmentList[0].DepartmentID);
                if (enableByDepartmentColorSheet)
                    styleClass = departmentPrototype.ButtonStyle;

                var labelText = departmentPrototype.Name;

                var departmentLabel = new Label
                {
                    Text = Loc.GetString(labelText) + ": " + departmentList.Count,
                    StyleClasses = { "LabelSecondaryColor" }
                };

                foreach (var player in departmentList)
                {
                    var playerButton = new Button
                    {
                        Text = player.Name,
                        TextAlign = Label.AlignMode.Right,
                        HorizontalAlignment = HAlignment.Center,
                        VerticalAlignment = VAlignment.Center,
                        SizeFlagsStretchRatio = 1,
                        StyleClasses = { styleClass },
                        ToolTip = player.JobName,
                        TooltipDelay = 0.1f,
                        SetWidth = 180,
                    };

                    playerButton.OnPressed += _ => WarpClicked?.Invoke(player.Entity);

                    departmentGrid.AddChild(playerButton);
                }

                bigGrid.AddChild(departmentLabel);
                bigGrid.AddChild(departmentGrid);
            }

            GhostTeleportContainer.AddChild(bigGrid);
        }

        private void AddPlaceButtons(List<GhostWarpPlace> places, string text, string styleClass)
        {
            if (places.Count == 0)
                return;

            var bigGrid = new GridContainer();

            var bigLabel = new Label
            {
                Text = Loc.GetString(text),
                StyleClasses = { "LabelBig" }
            };
            bigGrid.AddChild(bigLabel);

            var placesGrid = new GridContainer
            {
                Columns = 5,
            };

            var countLabel = new Label
            {
                Text = Loc.GetString("ghost-teleport-menu-count-label") + ": " + places.Count,
                StyleClasses = { "LabelSecondaryColor" }
            };

            foreach (var place in places)
            {
                var placeButton = new Button
                {
                    Text = place.Name,
                    TextAlign = Label.AlignMode.Right,
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                    SizeFlagsStretchRatio = 1,
                    StyleClasses = { styleClass },
                    ToolTip = place.Description,
                    TooltipDelay = 0.1f,
                    SetWidth = 180,
                };

                placeButton.OnPressed += _ => WarpClicked?.Invoke(place.Entity);

                placesGrid.AddChild(placeButton);
            }

            bigGrid.AddChild(countLabel);
            bigGrid.AddChild(placesGrid);

            GhostTeleportContainer.AddChild(bigGrid);
        }

        private void AddAntagButtons(List<GhostWarpGlobalAntagonist> antags, string text, string styleClass)
        {
            if (antags.Count == 0)
                return;

            var bigGrid = new GridContainer();

            var bigLabel = new Label
            {
                Text = Loc.GetString(text),
                StyleClasses = { "LabelBig" }
            };
            bigGrid.AddChild(bigLabel);

            var sortedAntags = SortAntagsByWeight(antags);

            foreach (var antagList in sortedAntags)
            {
                if (antagList.Count == 0)
                    continue;

                var departmentGrid = new GridContainer
                {
                    Columns = 5
                };

                var labelText = antagList[0].AntagonistName;

                foreach (var antag in antagList)
                {
                    var playerButton = new Button
                    {
                        Text = antag.Name,
                        TextAlign = Label.AlignMode.Right,
                        HorizontalAlignment = HAlignment.Center,
                        VerticalAlignment = VAlignment.Center,
                        SizeFlagsStretchRatio = 1,
                        StyleClasses = { styleClass },
                        ToolTip = Loc.GetString(antag.AntagonistDescription),
                        TooltipDelay = 0.1f,
                        SetWidth = 180,
                    };

                    playerButton.OnPressed += _ => WarpClicked?.Invoke(antag.Entity);

                    departmentGrid.AddChild(playerButton);
                }

                var departmentLabel = new Label
                {
                    Text = Loc.GetString(labelText) + $": {antagList.Count}",
                    StyleClasses = { "LabelSecondaryColor" }
                };

                bigGrid.AddChild(departmentLabel);
                bigGrid.AddChild(departmentGrid);
            }

            GhostTeleportContainer.AddChild(bigGrid);
        }

        public List<List<GhostWarpPlayer>> SortPlayersByDepartment(List<GhostWarpPlayer> players)
        {
            if (players.Count == 0)
                return new List<List<GhostWarpPlayer>>();

            return players
                .GroupBy(p => _prototypeManager.Index<DepartmentPrototype>(p.DepartmentID).Weight)
                .OrderByDescending(g => g.Key)
                .Select(g => g.ToList())
                .ToList();
        }

        public List<List<GhostWarpGlobalAntagonist>> SortAntagsByWeight(List<GhostWarpGlobalAntagonist> antagonists)
        {
            if (antagonists.Count == 0)
                return new List<List<GhostWarpGlobalAntagonist>>();

            return antagonists
                .GroupBy(a => _prototypeManager.Index<AntagonistPrototype>(a.PrototypeID).Weight)
                .OrderBy(g => g.Key)
                .Select(g => g.ToList())
                .ToList();
        }

        private List<GhostWarpPlace> GetSortedPlaces(List<GhostWarpPlace> places)
        {
            return places
                .OrderBy(w => w.Name)
                .ToList();
        }

        private List<GhostWarpPlayer> GetSortedPlayers(List<GhostWarpPlayer> players)
        {
            return players
                .OrderBy(w => w.Name)
                .ToList();
        }

        private List<GhostWarpGlobalAntagonist> GetSortedAntagonists(List<GhostWarpGlobalAntagonist> antagonists)
        {
            return antagonists
                .OrderBy(w => w.Name)
                .ToList();
        }

        private void PlayersAllocation()
        {
            _alivePlayers = _playerWarps.Where(warp => warp.IsAlive).ToList();
            _deadPlayers = _playerWarps.Where(warp => warp.IsDead).ToList();
            _leftPlayers = _playerWarps.Where(warp => warp.IsLeft).ToList();
            _ghostPlayers = _playerWarps.Where(warp => warp.IsGhost).ToList();
        }
    }
}
